### ISSUE TITLE
Cowboys/Ravens 12.08.2020 (Tuesday) Game

### ISSUE THREAD

**Issue by CL3000** [jbaum012/sports#5]
The Cowboys and Ravens play a rare Tuesday game for Week 13 (covid-related schedule change). When I entered it, it automatically put the game in Week 14 because of the Tuesday date. 

_(Note: Spread is intentionally empty b/c I couldn't find one listed yet)_

**Comment by jbaum012** [comment]
Will be fixed in version 2 where we will have more rigidly defined weeks. This wont be an issue in the future.
